import type { Document } from '../../types'
import { getDocumentLogoUrl } from './DocumentPanel'

// ── Shared: render the editor as a screenshot ───────────────────────
//
// Clones the live .tiptap editor, wraps it with a document header
// (title, meta, logo) and footer, then captures with html2canvas.
// Used by both PDF and DOCX exports for pixel-perfect output.

async function renderEditorScreenshot(
  doc: Document,
  opportunityName: string,
): Promise<HTMLCanvasElement> {
  const html2canvas = (await import('html2canvas-pro')).default
  const logoUrl = getDocumentLogoUrl(doc.id)
  const date = formatDate()

  // Find the live tiptap editor element
  const liveEditor = window.document.querySelector('.tiptap') as HTMLElement | null
  if (!liveEditor) throw new Error('Editor element not found')

  // Build an off-screen wrapper: header + cloned editor + footer
  const wrapper = window.document.createElement('div')
  wrapper.style.cssText = `
    position: fixed; left: -10000px; top: 0; z-index: -1;
    width: 780px; padding: 40px 40px 30px; background: white;
    font-family: ${getComputedStyle(liveEditor).fontFamily};
    color: #1a1a2e; line-height: 1.65;
  `

  // ── Header (display:table for html2canvas compatibility)
  const header = window.document.createElement('div')
  header.style.cssText = 'display:table;width:100%;margin-bottom:20px;padding-bottom:14px;border-bottom:2px solid #1a1a2e;'

  const headerLeft = window.document.createElement('div')
  headerLeft.style.cssText = 'display:table-cell;vertical-align:top;'
  headerLeft.innerHTML = `
    <div style="font-size:20px;font-weight:700;color:#1a1a2e;margin-bottom:4px;">${escapeHtml(doc.name)}</div>
    <div style="font-size:11px;color:#6b7280;">
      <span style="margin-right:14px;"><b>Opportunity:</b> ${escapeHtml(opportunityName)}</span>
      <span style="margin-right:14px;"><b>Date:</b> ${date}</span>
      <span><b>Status:</b> ${capitalize(doc.status.replace('_', ' '))}</span>
    </div>
  `
  header.appendChild(headerLeft)

  if (logoUrl) {
    const headerRight = window.document.createElement('div')
    headerRight.style.cssText = 'display:table-cell;vertical-align:top;text-align:right;width:160px;'
    const logoImg = window.document.createElement('img')
    logoImg.src = logoUrl
    logoImg.style.cssText = 'max-height:44px;max-width:150px;'
    await new Promise<void>((resolve) => {
      if (logoImg.complete && logoImg.naturalWidth > 0) return resolve()
      logoImg.onload = () => resolve()
      logoImg.onerror = () => resolve()
      setTimeout(resolve, 3000)
    })
    headerRight.appendChild(logoImg)
    header.appendChild(headerRight)
  }

  wrapper.appendChild(header)

  // ── Editor content: deep clone the live editor
  const editorClone = liveEditor.cloneNode(true) as HTMLElement
  editorClone.querySelectorAll('[data-drag-handle]').forEach((el) => {
    el.removeAttribute('data-drag-handle')
  })
  editorClone.style.outline = 'none'
  editorClone.style.padding = '0'
  editorClone.style.minHeight = 'auto'
  copyComputedStyles(liveEditor, editorClone)
  wrapper.appendChild(editorClone)

  // ── Footer
  const footer = window.document.createElement('div')
  footer.style.cssText = 'margin-top:30px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:9px;color:#9ca3af;text-align:center;'
  footer.textContent = `Generated by Invictus AI \u2022 ${date}`
  wrapper.appendChild(footer)

  window.document.body.appendChild(wrapper)

  // Wait for all cloned images to load
  const imgs = wrapper.querySelectorAll('img')
  await Promise.all(
    Array.from(imgs).map((img) =>
      img.complete ? Promise.resolve() : new Promise<void>((r) => { img.onload = () => r(); img.onerror = () => r() })
    ),
  )
  await sleep(100)

  try {
    const canvas = await html2canvas(wrapper, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      backgroundColor: '#ffffff',
    })
    return canvas
  } finally {
    window.document.body.removeChild(wrapper)
  }
}

// Copy computed styles from source to target recursively
function copyComputedStyles(source: HTMLElement, target: HTMLElement) {
  const props = [
    'font-family', 'font-size', 'font-weight', 'font-style',
    'color', 'text-decoration', 'text-align', 'line-height',
    'letter-spacing', 'white-space',
    'margin-top', 'margin-bottom', 'margin-left', 'margin-right',
    'padding-top', 'padding-bottom', 'padding-left', 'padding-right',
    'border-left', 'border-right', 'border-top', 'border-bottom',
    'background-color', 'list-style-type',
    'float', 'clear', 'display', 'width', 'max-width',
  ]

  const srcChildren = source.children
  const tgtChildren = target.children
  const len = Math.min(srcChildren.length, tgtChildren.length)

  for (let i = 0; i < len; i++) {
    const sc = srcChildren[i] as HTMLElement
    const tc = tgtChildren[i] as HTMLElement
    if (!sc || !tc) continue
    const computed = getComputedStyle(sc)
    for (const prop of props) {
      try { tc.style.setProperty(prop, computed.getPropertyValue(prop)) } catch { /* skip */ }
    }
    if (sc.children.length > 0) copyComputedStyles(sc, tc)
  }
}

// ── PDF Export ───────────────────────────────────────────────────────

export async function downloadAsPDF(doc: Document, opportunityName: string): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const canvas = await renderEditorScreenshot(doc, opportunityName)

  const imgData = canvas.toDataURL('image/png')
  const pdfW = 210 // A4 mm
  const pdfH = 297
  const margin = 10
  const contentW = pdfW - margin * 2
  const ratio = canvas.height / canvas.width
  const imgW = contentW
  const imgH = imgW * ratio

  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const pageH = pdfH - margin * 2

  if (imgH <= pageH) {
    pdf.addImage(imgData, 'PNG', margin, margin, imgW, imgH)
  } else {
    let pos = 0
    let page = 0
    while (pos < imgH) {
      if (page > 0) pdf.addPage()
      pdf.addImage(imgData, 'PNG', margin, margin - pos, imgW, imgH)
      pos += pageH
      page++
    }
  }

  pdf.save(`${sanitizeFilename(doc.name)}.pdf`)
}

// ── DOCX Export (screenshot-based, pixel-perfect) ───────────────────

export async function downloadAsDocx(doc: Document, opportunityName: string): Promise<void> {
  const docx = await import('docx')
  const { saveAs } = await import('file-saver')

  const canvas = await renderEditorScreenshot(doc, opportunityName)

  // Convert canvas to PNG bytes
  const pngDataUrl = canvas.toDataURL('image/png')
  const pngBytes = base64ToBytes(pngDataUrl)

  // A4 page: 595pt wide at 72 DPI. With 1-inch margins (72pt each side) = 451pt content width.
  // In docx library, dimensions are in pixels at ~96 DPI. Content width ≈ 600px.
  const docxContentWidth = 600
  const ratio = canvas.height / canvas.width
  const docxImgHeight = Math.round(docxContentWidth * ratio)

  const file = new docx.Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 500, right: 700, bottom: 500, left: 700 },
        },
      },
      children: [
        new docx.Paragraph({
          children: [
            new docx.ImageRun({
              data: pngBytes,
              transformation: { width: docxContentWidth, height: docxImgHeight },
              type: 'png',
            }),
          ],
        }),
      ],
    }],
  })

  const blob = await docx.Packer.toBlob(file)
  saveAs(blob, `${sanitizeFilename(doc.name)}.docx`)
}

// ── Utilities ───────────────────────────────────────────────────────

function base64ToBytes(dataUrl: string): Uint8Array {
  const raw = atob(dataUrl.split(',')[1] ?? '')
  const bytes = new Uint8Array(raw.length)
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i)
  return bytes
}

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}
function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
function sanitizeFilename(s: string): string {
  return s.replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '_')
}
function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}
