"""deals: add news_items and news_opportunity_links

Revision ID: 0697e7d079c8
Revises: eda7dc5d5c58
Create Date: 2026-04-13 10:51:21.154145
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0697e7d079c8'
down_revision: Union[str, None] = 'eda7dc5d5c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_news_items_tenant_id'), 'news_items', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_news_items_tenant', 'news_items', ['tenant_id'], unique=False, schema='deals')
    op.create_table('news_opportunity_links',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['deals.news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['deals.opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_item_id', 'opportunity_id'),
    schema='deals'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_opportunity_links', schema='deals')
    op.drop_index('ix_news_items_tenant', table_name='news_items', schema='deals')
    op.drop_index(op.f('ix_deals_news_items_tenant_id'), table_name='news_items', schema='deals')
    op.drop_table('news_items', schema='deals')
    # ### end Alembic commands ###
