"""initial schema

Revision ID: 2f3cb9c93004
Revises: 
Create Date: 2026-04-11 19:38:15.838351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3cb9c93004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='platform')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False, schema='admin')
    op.create_table('org_branding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('header_logo', sa.String(length=10), server_default='small', nullable=False),
    sa.Column('brand_color', sa.String(length=10), server_default='#000000', nullable=False),
    sa.Column('email_footer', sa.Text(), nullable=True),
    sa.Column('small_logo_url', sa.Text(), nullable=True),
    sa.Column('large_logo_url', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_org_branding_tenant_id'), 'org_branding', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_org_branding_tenant', 'org_branding', ['tenant_id'], unique=True, schema='admin')
    op.create_table('org_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_format', sa.String(length=20), server_default='MM/DD/YYYY', nullable=False),
    sa.Column('number_format', sa.String(length=20), server_default='en-US', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_org_preferences_tenant_id'), 'org_preferences', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_org_preferences_tenant', 'org_preferences', ['tenant_id'], unique=True, schema='admin')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True, schema='admin')
    op.create_index('ix_users_tenant_status', 'users', ['tenant_id', 'status'], unique=False, schema='admin')
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('module_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['admin.users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_invitations_tenant_created', 'invitations', ['tenant_id', 'created_at'], unique=False, schema='admin')
    op.create_table('user_module_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_slug', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_user_module_roles_tenant_id'), 'user_module_roles', ['tenant_id'], unique=False, schema='admin')
    op.create_index('ix_umr_tenant_user_module', 'user_module_roles', ['tenant_id', 'user_id', 'module_slug'], unique=True, schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_umr_tenant_user_module', table_name='user_module_roles', schema='admin')
    op.drop_index(op.f('ix_admin_user_module_roles_tenant_id'), table_name='user_module_roles', schema='admin')
    op.drop_table('user_module_roles', schema='admin')
    op.drop_index('ix_invitations_tenant_created', table_name='invitations', schema='admin')
    op.drop_index(op.f('ix_admin_invitations_tenant_id'), table_name='invitations', schema='admin')
    op.drop_table('invitations', schema='admin')
    op.drop_index('ix_users_tenant_status', table_name='users', schema='admin')
    op.drop_index('ix_users_tenant_email', table_name='users', schema='admin')
    op.drop_index(op.f('ix_admin_users_tenant_id'), table_name='users', schema='admin')
    op.drop_table('users', schema='admin')
    op.drop_index('ix_org_preferences_tenant', table_name='org_preferences', schema='admin')
    op.drop_index(op.f('ix_admin_org_preferences_tenant_id'), table_name='org_preferences', schema='admin')
    op.drop_table('org_preferences', schema='admin')
    op.drop_index('ix_org_branding_tenant', table_name='org_branding', schema='admin')
    op.drop_index(op.f('ix_admin_org_branding_tenant_id'), table_name='org_branding', schema='admin')
    op.drop_table('org_branding', schema='admin')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs', schema='admin')
    op.drop_index(op.f('ix_admin_audit_logs_tenant_id'), table_name='audit_logs', schema='admin')
    op.drop_table('audit_logs', schema='admin')
    op.drop_index(op.f('ix_platform_refresh_tokens_user_id'), table_name='refresh_tokens', schema='platform')
    op.drop_table('refresh_tokens', schema='platform')
    op.drop_table('organizations', schema='admin')
    # ### end Alembic commands ###
