"""deals: add documents, reviews, shares, source_files

Revision ID: 95660dd0b8b0
Revises: 0697e7d079c8
Create Date: 2026-04-13 11:16:39.185645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95660dd0b8b0'
down_revision: Union[str, None] = '0697e7d079c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('rationale_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_document_reviews_tenant_id'), 'document_reviews', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_document_reviews_reviewer_status', 'document_reviews', ['reviewer_id', 'status'], unique=False, schema='deals')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['deals.opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['deals.document_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_documents_tenant_id'), 'documents', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_documents_opportunity', 'documents', ['opportunity_id'], unique=False, schema='deals')
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('vector_store_id', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_origin', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['deals.opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_source_files_tenant_id'), 'source_files', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_source_files_opportunity', 'source_files', ['opportunity_id'], unique=False, schema='deals')
    op.create_table('document_review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['deals.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['deals.document_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'document_id', name='uq_document_review_items_review_document'),
    schema='deals'
    )
    op.create_table('document_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), server_default='comment', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['deals.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_document_shares_tenant_id'), 'document_shares', ['tenant_id'], unique=False, schema='deals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_document_shares_tenant_id'), table_name='document_shares', schema='deals')
    op.drop_table('document_shares', schema='deals')
    op.drop_table('document_review_items', schema='deals')
    op.drop_index('ix_source_files_opportunity', table_name='source_files', schema='deals')
    op.drop_index(op.f('ix_deals_source_files_tenant_id'), table_name='source_files', schema='deals')
    op.drop_table('source_files', schema='deals')
    op.drop_index('ix_documents_opportunity', table_name='documents', schema='deals')
    op.drop_index(op.f('ix_deals_documents_tenant_id'), table_name='documents', schema='deals')
    op.drop_table('documents', schema='deals')
    op.drop_index('ix_document_reviews_reviewer_status', table_name='document_reviews', schema='deals')
    op.drop_index(op.f('ix_deals_document_reviews_tenant_id'), table_name='document_reviews', schema='deals')
    op.drop_table('document_reviews', schema='deals')
    # ### end Alembic commands ###
