"""deals: add email and google drive integration tables

Revision ID: c7717d8c0df3
Revises: 95660dd0b8b0
Create Date: 2026-04-13 11:37:04.702158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7717d8c0df3'
down_revision: Union[str, None] = '95660dd0b8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), server_default='gmail', nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_labels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='connected', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_email_accounts_tenant_id'), 'email_accounts', ['tenant_id'], unique=False, schema='deals')
    op.create_table('google_drive_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='connected', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_google_drive_accounts_tenant_id'), 'google_drive_accounts', ['tenant_id'], unique=False, schema='deals')
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_account_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('import_status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['deals.email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_emails_tenant_id'), 'emails', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_emails_tenant_account', 'emails', ['tenant_id', 'email_account_id'], unique=False, schema='deals')
    op.create_index('ix_emails_tenant_import_status', 'emails', ['tenant_id', 'import_status'], unique=False, schema='deals')
    op.create_table('google_drive_import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('folder_paths', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('total_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('opportunities_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['deals.google_drive_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_google_drive_import_jobs_tenant_id'), 'google_drive_import_jobs', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_google_drive_import_jobs_tenant_status', 'google_drive_import_jobs', ['tenant_id', 'status'], unique=False, schema='deals')
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['deals.emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_attachments', schema='deals')
    op.drop_index('ix_google_drive_import_jobs_tenant_status', table_name='google_drive_import_jobs', schema='deals')
    op.drop_index(op.f('ix_deals_google_drive_import_jobs_tenant_id'), table_name='google_drive_import_jobs', schema='deals')
    op.drop_table('google_drive_import_jobs', schema='deals')
    op.drop_index('ix_emails_tenant_import_status', table_name='emails', schema='deals')
    op.drop_index('ix_emails_tenant_account', table_name='emails', schema='deals')
    op.drop_index(op.f('ix_deals_emails_tenant_id'), table_name='emails', schema='deals')
    op.drop_table('emails', schema='deals')
    op.drop_index(op.f('ix_deals_google_drive_accounts_tenant_id'), table_name='google_drive_accounts', schema='deals')
    op.drop_table('google_drive_accounts', schema='deals')
    op.drop_index(op.f('ix_deals_email_accounts_tenant_id'), table_name='email_accounts', schema='deals')
    op.drop_table('email_accounts', schema='deals')
    # ### end Alembic commands ###
