"""deals: add core tables

Revision ID: eda7dc5d5c58
Revises: 2f3cb9c93004
Create Date: 2026-04-12 12:30:11.578453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda7dc5d5c58'
down_revision: Union[str, None] = '2f3cb9c93004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fund_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('firm_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by_type', sa.String(length=50), server_default='system', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index('ix_asset_managers_tenant', 'asset_managers', ['tenant_id'], unique=False, schema='deals')
    op.create_index(op.f('ix_deals_asset_managers_tenant_id'), 'asset_managers', ['tenant_id'], unique=False, schema='deals')
    op.create_table('investment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snapshot_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_investment_types_tenant_slug'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_investment_types_tenant_id'), 'investment_types', ['tenant_id'], unique=False, schema='deals')
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('target_allocation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expected_return', sa.String(length=100), nullable=True),
    sa.Column('time_horizon', sa.String(length=100), nullable=True),
    sa.Column('investment_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('asset_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_sectors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('geographic_focus', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('investment_criteria', sa.Text(), nullable=True),
    sa.Column('investment_constraints', sa.Text(), nullable=True),
    sa.Column('investment_strategy', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_mandates_tenant_id'), 'mandates', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_mandates_tenant_status', 'mandates', ['tenant_id', 'status'], unique=False, schema='deals')
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investment_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_type_id'], ['deals.investment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'investment_type_id', 'slug', name='uq_document_templates_tenant_type_slug'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False, schema='deals')
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('investment_type_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('asset_manager_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('snapshot_citations', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_type', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('source_email_id', sa.UUID(), nullable=True),
    sa.Column('mandate_fits', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_manager_id'], ['deals.asset_managers.id'], ),
    sa.ForeignKeyConstraint(['investment_type_id'], ['deals.investment_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['admin.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deals'
    )
    op.create_index(op.f('ix_deals_opportunities_tenant_id'), 'opportunities', ['tenant_id'], unique=False, schema='deals')
    op.create_index('ix_opportunities_asset_manager', 'opportunities', ['asset_manager_id'], unique=False, schema='deals')
    op.create_index('ix_opportunities_tenant_assigned', 'opportunities', ['tenant_id', 'assigned_to'], unique=False, schema='deals')
    op.create_index('ix_opportunities_tenant_pipeline', 'opportunities', ['tenant_id', 'pipeline_status'], unique=False, schema='deals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opportunities_tenant_pipeline', table_name='opportunities', schema='deals')
    op.drop_index('ix_opportunities_tenant_assigned', table_name='opportunities', schema='deals')
    op.drop_index('ix_opportunities_asset_manager', table_name='opportunities', schema='deals')
    op.drop_index(op.f('ix_deals_opportunities_tenant_id'), table_name='opportunities', schema='deals')
    op.drop_table('opportunities', schema='deals')
    op.drop_index(op.f('ix_deals_document_templates_tenant_id'), table_name='document_templates', schema='deals')
    op.drop_table('document_templates', schema='deals')
    op.drop_index('ix_mandates_tenant_status', table_name='mandates', schema='deals')
    op.drop_index(op.f('ix_deals_mandates_tenant_id'), table_name='mandates', schema='deals')
    op.drop_table('mandates', schema='deals')
    op.drop_index(op.f('ix_deals_investment_types_tenant_id'), table_name='investment_types', schema='deals')
    op.drop_table('investment_types', schema='deals')
    op.drop_index(op.f('ix_deals_asset_managers_tenant_id'), table_name='asset_managers', schema='deals')
    op.drop_index('ix_asset_managers_tenant', table_name='asset_managers', schema='deals')
    op.drop_table('asset_managers', schema='deals')
    # ### end Alembic commands ###
